# config.py

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"

DB_PATH = DATA_DIR / "queue.db"
SECRET_KEY_PATH = DATA_DIR / "secret.key"

FACE_MODEL_NAME = "buffalo_s"

DET_SCORE_THRESHOLD = 0.70
SIMILARITY_THRESHOLD = 0.48

MAX_QUEUE = 3
MAX_PRINT_PER_FACE = 1

CAMERA_INDEX = 0
WINDOW_NAME = "Face Queue Scanner"

STARTUP_COOLDOWN_SECONDS = 20
CAPTURE_COOLDOWN_SECONDS = 20

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

SCAN_SLEEP_SECONDS = 0.08
WAIT_SLEEP_SECONDS = 0.5

JPEG_QUALITY = 60
VIDEO_STREAM_SLEEP_SECONDS = 0.08
VIDEO_IDLE_SLEEP_SECONDS = 0.5

AUTO_CAPTURE_STABLE_SECONDS = 2.0
RESULT_DISPLAY_SECONDS = 3